Drafter/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin
from wwe.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^wwe/', include('wwe.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wwe/urls.py
from django.conf.urls import url
from . import views

app_name = 'wwe'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='home'),

    # /wwe/brands
    url(r'^brands/$', views.BrandsView.as_view(), name='brands'),

    # /wwe/brand/raw
    url(r'^brand/(?P<slug>[\w-]+)$', views.BrandView.as_view(), name='brand'),

    # /wwe/brand/add
    url(r'^brand/add/$', views.BrandCreate.as_view(), name='brand-add'),

    # /wwe/brand/raw/update
    url(r'^brand/(?P<slug>[\w-]+)/update/$', views.BrandUpdate.as_view(), name='brand-update'),

    # /wwe/brand/raw/delete
    url(r'^brand/(?P<slug>[\w-]+)/delete/$', views.BrandDelete.as_view(), name='brand-delete'),

    # /wwe/wrestlers
    url(r'^wrestlers/$', views.WrestlersView.as_view(), name='wrestlers'),

    # /wwe/wrestler/undertaker
    url(r'^wrestler/(?P<slug>[\w-]+)$', views.WrestlerView.as_view(), name='wrestler'),

    # /wwe/wrestler/add
    url(r'^wrestler/add/$', views.WrestlerCreate.as_view(), name='wrestler-add'),

    # /wwe/wrestler/undertaker/update
    url(r'^wrestler/(?P<slug>[\w-]+)/update/$', views.WrestlerUpdate.as_view(), name='wrestler-update'),

    # /wwe/wrestler/undertaker/delete
    url(r'^wrestler/(?P<slug>[\w-]+)/delete/$', views.WrestlerDelete.as_view(), name='wrestler-delete'),

    # /wwe/tagteams
    url(r'^tagteams/$', views.TagTeamsView.as_view(), name='tagteams'),

    # /wwe/tagteam/nwo
    url(r'^tagteam/(?P<slug>[\w-]+)$', views.TagTeamView.as_view(), name='tagteam'),

    # /wwe/tagteam/add
    url(r'^tagteam/add/$', views.TagTeamCreate.as_view(), name='tagteam-add'),

    # /wwe/tagteam/nwo/update
    url(r'^tagteam/(?P<slug>[\w-]+)/update/$', views.TagTeamUpdate.as_view(), name='tagteam-update'),

    # /wwe/tagteam/nwo/delete
    url(r'^tagteam/(?P<slug>[\w-]+)/delete/$', views.TagTeamDelete.as_view(), name='tagteam-delete'),

    # /wwe/championships
    url(r'^championships/$', views.ChampionshipsView.as_view(), name='championships'),

    # /wwe/championship/templates.wwe
    url(r'^championship/(?P<slug>[\w-]+)$', views.ChampionshipView.as_view(), name='championship'),

    # /wwe/championship/add
    url(r'^championship/add/$', views.ChampionshipCreate.as_view(), name='championship-add'),

    # /wwe/championship/templates.wwe/update
    url(r'^championship/(?P<slug>[\w-]+)/update/$', views.ChampionshipUpdate.as_view(), name='championship-update'),

    # /wwe/championship/templates.wwe/delete
    url(r'^championship/(?P<slug>[\w-]+)/delete/$', views.ChampionshipDelete.as_view(), name='championship-delete'),

    # /wwe/events
    url(r'^events/$', views.EventsView.as_view(), name='events'),

    # /wwe/event/wrestlemania
    url(r'^event/(?P<slug>[\w-]+)$', views.EventView.as_view(), name='event'),

    # /wwe/event/add
    url(r'^event/add/$', views.EventCreate.as_view(), name='event-add'),

    # /wwe/event/wrestlemania/update
    url(r'^event/(?P<slug>[\w-]+)/update/$', views.EventUpdate.as_view(), name='event-update'),

    # /wwe/event/wrestlemania/delete
    url(r'^event/(?P<slug>[\w-]+)/delete/$', views.EventDelete.as_view(), name='event-delete'),

    # /wwe/matchtypes
    url(r'^matchtypes/$', views.MatchTypesView.as_view(), name='matchtypes'),

    # /wwe/matchtype/triple-threat
    url(r'^matchtype/(?P<slug>[\w-]+)$', views.MatchTypeView.as_view(), name='matchtype'),

    # /wwe/matchtype/add
    url(r'^matchtype/add/$', views.MatchTypeCreate.as_view(), name='matchtype-add'),

    # /wwe/matchtype/triple-threat/update
    url(r'^matchtype/(?P<slug>[\w-]+)/update/$', views.MatchTypeUpdate.as_view(), name='matchtype-update'),

    # /wwe/matchtype/triple-threat/delete
    url(r'^matchtype/(?P<slug>[\w-]+)/delete/$', views.MatchTypeDelete.as_view(), name='matchtype-delete'),

    # /wwe/match/add
    url(r'^match/add/$', views.MatchCreate.as_view(), name='match-add'),

    # /wwe/match/1/delete
    url(r'^match/(?P<pk>[0-9]+)/delete/$', views.MatchDelete.as_view(), name='tagmatch-delete'),

    # /wwe/match/tagteam/add
    url(r'^tagmatch/add/$', views.TagTeamMatchCreate.as_view(), name='tagmatch-add'),

    # /wwe/tagmatch/1/delete
    url(r'^tagmatch/(?P<pk>[0-9]+)/delete/$', views.TagTeamMatchDelete.as_view(), name='tagmatch-delete'),

    # /wwe/drafts
    url(r'^drafts/', views.DraftsView.as_view(), name='drafts'),

    # /wwe/drafthistory/save
    url(r'^drafthistory/create/$', views.DraftHistoryCreate.as_view(), name='drafthistory-add'),

    # /wwe/draft/delete
    url(r'^draft/delete/$', views.DraftDelete.as_view(), name='draft-delete'),

    # /wwe/ajax/wrestlers
    url(r'^api/wrestlers/$', views.get_wrestlers, name='wrestlers-api'),
]

wwe/models.py
from django.urls import reverse
from django.db import models
from django.db.models.query import QuerySet
from django.utils.text import slugify
from django.utils import timezone
from django_countries.fields import CountryField
import jsonfield
from common.models import SoftDeletionModel, TimestampModel

INACTIVE = False
ACTIVE = True
STATUS_CHOICES = (
    (ACTIVE, 'Active'),
    (INACTIVE, 'Inactive'),
)

class Brand(SoftDeletionModel):
    slug = models.SlugField(max_length=40, unique=True)
    name = models.CharField(max_length=250, unique=True)
    color = models.CharField(max_length=20, default='black')
    status = models.BooleanField(choices=STATUS_CHOICES, default=ACTIVE)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse('wwe:brands')

    @staticmethod
    def db_fields():
        return ['name', 'color']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Brand, self).save(*args, **kwargs)


class Wrestler(SoftDeletionModel):
    slug = models.SlugField(max_length=40, unique=True)
    name = models.CharField(max_length=250, unique=True)
    ovr = models.PositiveIntegerField(default=0)
    country = CountryField(blank_label='( Select country )', blank=True)
    brand = models.ForeignKey(Brand, blank=True, default='', null=True, on_delete=models.SET_DEFAULT)
    height = models.PositiveIntegerField(null=True, blank=True)
    weight = models.PositiveIntegerField(null=True, blank=True)
    original_primary = models.PositiveIntegerField(default=0)
    original_secondary = models.PositiveIntegerField(default=0)
    primary = models.PositiveIntegerField(default=0)
    secondary = models.PositiveIntegerField(default=0)
    tertiary = models.PositiveIntegerField(default=0)
    tag_team = models.PositiveIntegerField(default=0)
    image_url = models.CharField(max_length=300)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse('wwe:wrestler-add')

    def original_titles(self):
        return self.original_primary + self.original_secondary

    def total_titles(self):
        return self.primary + self.secondary + self.tertiary + self.tag_team

    def total_points(self):
        return (3 * self.primary) + (2 * self.secondary) + (1 * self.tertiary) + (1 * self.tag_team) + (0.5 * self.ovr) + (self.original_primary)

    @staticmethod
    def db_fields():
        return [
            'name', 'ovr', 'country', 'brand', 'height', 'weight', 'original_primary',
            'original_secondary', 'primary', 'secondary', 'tertiary', 'tag_team', 'image_url'
        ]

    def save(self, *args, **kwargs):
        if not self.country:
            self.country = 'US'

        self.slug = slugify(self.name)
        return super(Wrestler, self).save(*args, **kwargs)


class TagTeam(SoftDeletionModel):
    slug = models.SlugField(max_length=40, unique=True)
    name = models.CharField(max_length=250, unique=True)
    members = models.ManyToManyField(Wrestler)

    class Meta:
        verbose_name_plural = 'tagteams'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('wwe:tagteam', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(TagTeam, self).save(*args, **kwargs)


class Championship(SoftDeletionModel):
    PRIMARY = 'PR'
    SECONDARY = 'SE'
    TERTIARY = 'TE'
    TAG_TEAM = 'TT'
    BELT_TYPE_CHOICES = (
        (PRIMARY, 'Primary'),
        (SECONDARY, 'Secondary'),
        (TERTIARY, 'Tertiary'),
        (TAG_TEAM, 'Tag Team'),
    )
    slug = models.SlugField(max_length=40, unique=True)
    name = models.CharField(max_length=250, unique=True)
    belt_type = models.CharField(choices=BELT_TYPE_CHOICES, max_length=2, default=PRIMARY)
    status = models.BooleanField(choices=STATUS_CHOICES, default=ACTIVE)
    champion = models.ManyToManyField(Wrestler, blank=True, default='')
    image_url = models.CharField(max_length=300)

    def __str__(self):
        return self.name

    def is_tag_team(self):
        return self.belt_type in self.TAG_TEAM

    def get_absolute_url(self):
        return reverse('wwe:championship', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Championship, self).save(*args, **kwargs)


class Event(SoftDeletionModel):
    slug = models.SlugField(max_length=40, unique=True)
    name = models.CharField(max_length=250)
    year = models.CharField(max_length=4)
    brand = models.ForeignKey(Brand, blank=True, default='', null=True, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['name', 'year']

    def __str__(self):
        return "%s (%s)" % (self.name, self.year)

    def get_absolute_url(self):
        return reverse('wwe:event', kwargs={'slug': self.slug})

    @staticmethod
    def db_fields():
        return ['name', 'brand', 'year']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.__str__)
        return super(Event, self).save(*args, **kwargs)


class MatchType(SoftDeletionModel):
    slug = models.SlugField(max_length=40, unique=True)
    name = models.CharField(max_length=250, unique=True)
    no_of_participants = models.PositiveIntegerField(default=2)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse('wwe:matchtype-add')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(MatchType, self).save(*args, **kwargs)


class Match(TimestampModel):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    championship = models.ForeignKey(Championship, null=True, blank=True, on_delete=models.CASCADE)
    match_type = models.ForeignKey(MatchType, blank=True, default='', on_delete=models.CASCADE)
    participants = models.ManyToManyField(Wrestler, blank=True, related_name='participants')
    winner = models.ForeignKey(Wrestler, blank=True, related_name='winner', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return "%s (%s)" % (self.event, self.championship)

    class Meta:
        verbose_name_plural = 'matches'


class TagTeamMatch(TimestampModel):
    TEAM1 = 't1'
    TEAM2 = 't2'
    WINNER_CHOICES = (
        (TEAM1, 'Team 1'),
        (TEAM2, 'Team 2'),
    )
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    tag_championship = models.ForeignKey(Championship, null=True, blank=True, on_delete=models.CASCADE)
    team1 = models.ManyToManyField(Wrestler, related_name='team1', blank=True)
    team2 = models.ManyToManyField(Wrestler, related_name='team2', blank=True)
    tag_winner = models.CharField(choices=WINNER_CHOICES, default=TEAM1, max_length=2)

    def __str__(self):
        return "%s (%s)" % (self.event, self.tag_championship)

    class Meta:
        verbose_name_plural = 'tag_team_matches'


class ChampionshipHistory(TimestampModel):
    match = models.ForeignKey(Match, null=True, blank=True, on_delete=models.CASCADE)
    tag_match = models.ForeignKey(TagTeamMatch, null=True, blank=True, on_delete=models.CASCADE)
    old_champion = models.ManyToManyField(Wrestler, blank=True, related_name='old_champion')
    new_champion = models.ManyToManyField(Wrestler, blank=True, related_name='new_champion')

    def __str__(self):
        return "%s / %s" % (self.match, self.tag_match)

    class Meta:
        verbose_name_plural = 'championship_history'


class DraftHistory(SoftDeletionModel):
    name = models.CharField(max_length=200, null=True, blank=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    data = jsonfield.JSONField()

    class Meta:
        verbose_name_plural = 'draft_history'
        unique_together = ['name', 'brand']


class TemporaryDraft(TimestampModel):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    wrestlers = models.ManyToManyField(Wrestler, blank=True)

wwe/forms.py
from .models import Wrestler, TagTeam, Championship, Event, Match, TagTeamMatch, MatchType
from django.forms import ModelForm, TextInput, CharField, HiddenInput, ModelChoiceField


class WrestlerForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(WrestlerForm, self).__init__(*args, **kwargs)
        self.fields['brand'].empty_label = ''

    class Meta:
        model = Wrestler
        fields = ['name', 'ovr', 'country', 'brand', 'height', 'weight', 'original_primary', 'original_secondary',
                  'primary', 'secondary', 'tertiary', 'tag_team']


class TagTeamForm(ModelForm):
    class Meta:
        model = TagTeam
        fields = ['name', 'members']


class ChampionshipForm(ModelForm):
    class Meta:
        model = Championship
        fields = ['name', 'belt_type', 'status', 'champion']


class MatchForm(ModelForm):
    def __init__(self, *args, **kwargs):
        exclude_event = kwargs.pop('exclude_event', None)
        super(MatchForm, self).__init__(*args, **kwargs)
        self.fields['event'].empty_label = ''
        self.fields['championship'] = ModelChoiceField(queryset=Championship.objects.exclude(belt_type='TT'))
        self.fields['championship'].empty_label = ''
        self.fields['match_type'].empty_label = ''
        self.fields['winner'] = CharField(required=False, widget=TextInput(attrs={'class': 'autocomplete'}))
        if exclude_event:
            self.fields['event'].widget = HiddenInput()

    class Meta:
        model = Match
        fields = ['event', 'championship', 'match_type', 'participants']


class TagMatchForm(ModelForm):
    def __init__(self, *args, **kwargs):
        exclude_event = kwargs.pop('exclude_event', None)
        super(TagMatchForm, self).__init__(*args, **kwargs)
        self.fields['event'].empty_label = ''
        self.fields['tag_championship'] = ModelChoiceField(queryset=Championship.objects.filter(belt_type='TT'))
        self.fields['tag_championship'].empty_label = ''
        if exclude_event:
            self.fields['event'].widget = HiddenInput()

    class Meta:
        model = TagTeamMatch
        fields = ['event', 'tag_championship', 'team1', 'team2', 'tag_winner']

wwe/templates/wwe/forms/create/brand.html
{% extends 'wwe/base.html' %}
{% block title %}Save Brand{% endblock %}

{% block body %}
<section>
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card z-depth-5">
				<div class="card-content">
					<span class="card-title">Save Brand</span>
					<form action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'wwe/forms/template.html' %}
						{% include 'wwe/forms/error.html' %}
						<div class="row">
							<div class="input-field col s12">
								<button class="btn waves-effect waves-light green lighten-1" type="submit">Save Brand
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

wwe/templates/wwe/forms/create/championship.html
{% extends 'wwe/base.html' %}
{% block title %}Save Championship{% endblock %}

{% block body %}
<section>
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card z-depth-5">
				<div class="card-content">
					<span class="card-title">Save Championship</span>
					{% csrf_token %}
					{% include 'wwe/forms/template.html' %}
					<div class="card z-depth-3 red" id="error-parent" style="display: none;">
						<div class="card-content" id="error"></div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<button class="btn waves-effect waves-light green lighten-1" id="submit">Save Championship
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

{% block script %}
<script>
	$(document).ready(() => {
		getWrestlersData('champion');
		$('#submit').click((e) => {
			const chipData = $('#id_champion').material_chip('data');
			const options = [];
			chipData.forEach(el => {
				options.push(el.tag);
			});
			const name = $('#id_name').val();
			const csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val();
			const belt_type = $('#id_belt_type').val();
			$.post("/wwe/championship/add/", {
				name, csrfmiddlewaretoken, belt_type, champions_list: options,
			},
			(response, status) => {
				handleFormResponse(response);
			});
		});
	});
</script>
{% endblock %}

wwe/templates/wwe/forms/create/event.html
{% extends 'wwe/base.html' %}
{% block title %}Save Event{% endblock %}

{% block body %}
<section>
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card z-depth-5">
				<div class="card-content">
					<span class="card-title">Save Event</span>
					<form action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'wwe/forms/template.html' %}
						{% include 'wwe/forms/error.html' %}
						<div class="row">
							<div class="input-field col s12">
								<button class="btn waves-effect waves-light green lighten-1" type="submit">Save Event
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

wwe/templates/wwe/forms/create/match.html
{% extends 'wwe/base.html' %}
{% block title %}Save Match{% endblock %}

{% block body %}
<section>
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card z-depth-5">
				<div class="card-content">
					<span class="card-title">Save Match</span>
					{% csrf_token %}
					{% include 'wwe/forms/template.html' %}
					<div class="card z-depth-3 red" id="error-parent" style="display: none;">
						<div class="card-content" id="error"></div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<button class="btn waves-effect waves-light green lighten-1" id="submit">Save Match
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

{% block script %}
<script>
	function setAutocompleteData() {
		const chipData = $('#id_participants').material_chip('data');
		const customData = {};
		chipData.forEach(el => {
			customData[el.tag] = null;
		});
		$('#id_winner').autocomplete({
			data: customData,
			minLength: 1,
		});
	}

	$(document).ready(() => {
		getWrestlersData('participants');
		$('#id_participants').on('chip.add', (e, chip) => {
			setAutocompleteData();
		});
		$('#id_participants').on('chip.delete', (e, chip) => {
			setAutocompleteData();
		});
		$('#submit').click((e) => {
			const chipData = $('#id_participants').material_chip('data');
			const options = [];
			chipData.forEach(el => {
				options.push(el.tag);
			});
			const event = $('#id_event').val();
			const championship = $('#id_championship').val();
			const match_type = $('#id_match_type').val();
			const new_champion = $('#id_winner').val();
			const csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val();
			$.post("/wwe/match/add/", {
				event,
				championship,
				match_type,
				new_champion,
				csrfmiddlewaretoken,
				participants_list: options,
			},
			(response, status) => {
				handleFormResponse(response);
			});
		});
	});
</script>
{% endblock %}

wwe/templates/wwe/forms/create/match_type.html
{% extends 'wwe/base.html' %}
{% block title %}Save Match Type{% endblock %}

{% block body %}
<section>
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card z-depth-5">
				<div class="card-content">
					<span class="card-title">Save Match Type</span>
					<form action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'wwe/forms/template.html' %}
						{% include 'wwe/forms/error.html' %}
						<div class="row">
							<div class="input-field col s12">
								<button class="btn waves-effect waves-light green lighten-1" type="submit">Save Match Type
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

wwe/templates/wwe/forms/create/tag_team.html
{% extends 'wwe/base.html' %}
{% block title %}Save Tag Team{% endblock %}

{% block body %}
<section>
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card z-depth-5">
				<div class="card-content">
					<span class="card-title">Save Tag Team</span>
					{% csrf_token %}
					{% include 'wwe/forms/template.html' %}
					<div class="card z-depth-3 red" id="error-parent" style="display: none;">
						<div class="card-content" id="error"></div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<button class="btn waves-effect waves-light green lighten-1" id="submit">Save Tag Team
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

{% block script %}
<script>
	$(document).ready(() => {
		getWrestlersData('members');
		$('#submit').click((e) => {
			const chipData = $('#id_members').material_chip('data');
			const options = [];
			chipData.forEach(el => {
				options.push(el.tag);
			});
			const name = $('#id_name').val();
			const csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val();
			$.post("/wwe/tagteam/add/", {
				name, csrfmiddlewaretoken, members_list: options,
			},
			(response, status) => {
				handleFormResponse(response);
			});
		});
	});
</script>
{% endblock %}

wwe/templates/wwe/forms/create/tag_team_match.html
{% extends 'wwe/base.html' %}
{% block title %}Save Tag Team Match{% endblock %}

{% block body %}
<section>
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card z-depth-5">
				<div class="card-content">
					<span class="card-title">Save Tag Match</span>
					{% csrf_token %}
					{% include 'wwe/forms/template.html' %}
					{% include 'wwe/forms/error.html' %}
					<div class="row">
						<div class="input-field col s12">
							<button class="btn waves-effect waves-light green lighten-1" id="submit">Save Match
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

{% block script %}
<script>
	$(document).ready(() => {
		getWrestlersData(['team1', 'team2']);
		$('#submit').click((e) => {
			const team1Data = $('#id_team1').material_chip('data');
			const team2Data = $('#id_team2').material_chip('data');
			const options = {
				team1: [], team2: [],
			};
			team1Data.forEach(el => {
				options.team1.push(el.tag);
			});
			team2Data.forEach(el => {
				options.team2.push(el.tag);
			});
			const event = $('#id_event').val();
			const tag_championship = $('#id_tag_championship').val();
			const tag_winner = $('#id_tag_winner').val();
			const csrfmiddlewaretoken = $('input[name=csrfmiddlewaretoken]').val();
			$.post("/wwe/tagmatch/add/", {
				event,
				tag_championship,
				tag_winner,
				csrfmiddlewaretoken,
				team1_list: options.team1,
				team2_list: options.team2,
			},
			(response, status) => {
				handleFormResponse(response);
			});
		});
	});
</script>
{% endblock %}

wwe/templates/wwe/forms/create/wrestler.html
{% extends 'wwe/base.html' %}
{% block title %}Save Superstar{% endblock %}

{% block body %}
<section>
	<div class="row">
		<div class="col s12 m8 offset-m2">
			<div class="card z-depth-5">
				<div class="card-content">
					<span class="card-title">Save Superstar</span>
					<form action="" method="POST" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'wwe/forms/template.html' %}
						{% include 'wwe/forms/error.html' %}
						<div class="row">
							<div class="input-field col s12">
								<button class="btn waves-effect waves-light green lighten-1" type="submit">Save Superstar
									<span><i class="fa fa-user"></i></span>
								</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}